<a href="https://colab.research.google.com/github/MariamRaafatMohamed/Pandas/blob/main/Exercises_(7).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# United States - Crime Rates - 1960 - 2014

### Introduction:

This time you will create a data

Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [ ]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/US_Crime_Rates/US_Crime_Rates_1960_2014.csv")

df.head()

,Year,Population,Total,Violent,Property,Murder,Forcible_Rape,Robbery,Aggravated_assault,Burglary,Larceny_Theft,Vehicle_Theft
0,1960,179323175,3384200,288460,3095700,9110,17190,107840,154320,912100,1855400,328200
1,1961,182992000,3488000,289390,3198600,8740,17220,106670,156760,949600,1913000,336000
2,1962,185771000,3752200,301510,3450700,8530,17550,110860,164570,994300,2089600,366800
3,1963,188483000,4109500,316970,3792500,8640,17650,116470,174210,1086400,2297800,408300
4,1964,191141000,4564600,364220,4200400,9360,21420,130390,203050,1213200,2514400,472800

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/US_Crime_Rates/US_Crime_Rates_1960_2014.csv).

### Step 3. Assign it to a variable called crime.

In [ ]:
crime = pd.read_csv("https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/US_Crime_Rates/US_Crime_Rates_1960_2014.csv")

### Step 4. What is the type of the columns?

In [ ]:
crime.dtypes

Year                  int64
Population            int64
Total                 int64
Violent               int64
Property              int64
Murder                int64
Forcible_Rape         int64
Robbery               int64
Aggravated_assault    int64
Burglary              int64
Larceny_Theft         int64
Vehicle_Theft         int64
dtype: object

##### Have you noticed that the type of Year is int64. But pandas has a different type to work with Time Series. Let's see it now.

### Step 5. Convert the type of the column Year to datetime64

In [ ]:
crime['Year'] = pd.to_datetime(crime['Year'])

crime.dtypes['Year']

dtype('<M8[ns]')

### Step 6. Set the Year column as the index of the dataframe

In [ ]:
crime.set_index('Year')
crime.head()

,Year,Population,Total,Violent,Property,Murder,Forcible_Rape,Robbery,Aggravated_assault,Burglary,Larceny_Theft,Vehicle_Theft
0,1960-01-01,179323175,3384200,288460,3095700,9110,17190,107840,154320,912100,1855400,328200
1,1961-01-01,182992000,3488000,289390,3198600,8740,17220,106670,156760,949600,1913000,336000
2,1962-01-01,185771000,3752200,301510,3450700,8530,17550,110860,164570,994300,2089600,366800
3,1963-01-01,188483000,4109500,316970,3792500,8640,17650,116470,174210,1086400,2297800,408300
4,1964-01-01,191141000,4564600,364220,4200400,9360,21420,130390,203050,1213200,2514400,472800

### Step 7. Delete the Total column

In [ ]:
 crime = crime.drop(columns='Total')

crime.columns

Index(['Year', 'Population', 'Violent', 'Property', 'Murder', 'Forcible_Rape',
       'Robbery', 'Aggravated_assault', 'Burglary', 'Larceny_Theft',
       'Vehicle_Theft'],
      dtype='object')

### Step 8. Group the year by decades and sum the values

#### Pay attention to the Population column number, summing this column is a mistake

In [ ]:
crime['Decade'] = (crime.index // 10) * 10

crime.groupby('Decade').sum(numeric_only=True)

,Population,Violent,Property,Murder,Forcible_Rape,Robbery,Aggravated_assault,Burglary,Larceny_Theft,Vehicle_Theft,Total_Crimes
Decade,,,,,,,,,,,
0,1915053175,4134930,45160900,106180,236720,1633510,2158520,13321100,26547700,5292100,49295830
10,2121193298,9607930,91383800,192230,554570,4159020,4702120,28486000,53157800,9739900,100991730
20,2371370069,14074328,117048900,206439,865639,5383109,7619130,33073494,72040253,11935411,131123228
30,2612825258,17527048,119053499,211664,998827,5748930,10568963,26750015,77679366,14624418,136580547
40,2947969117,13968056,100944369,163068,922499,4230366,8652124,21565176,67970291,11412834,114912425
50,1570146307,6072017,44095950,72867,421059,1749809,3764142,10125170,30401698,3569080,50167967

### Step 9. What is the most dangerous decade to live in the US?

In [ ]:
crime['Total_Crimes'] = crime['Violent'] + crime['Property']

crimes_per_decade = crime.groupby('Decade')['Total_Crimes'].sum().idxmax()

Decade
0      49295830
10    100991730
20    131123228
30    136580547
40    114912425
50     50167967
Name: Total_Crimes, dtype: int64

np.int64(30)