<a href="https://colab.research.google.com/github/MariamRaafatMohamed/Pandas/blob/main/Exercises_(8).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# MPG Cars

### Introduction:

The following exercise utilizes data from [UC Irvine Machine Learning Repository](https://archive.ics.uci.edu/ml/datasets/Auto+MPG)

### Step 1. Import the necessary libraries

In [2]:
import pandas as pd

### Step 2. Import the first dataset [cars1](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv) and [cars2](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv).

   ### Step 3. Assign each to a variable called cars1 and cars2

In [4]:
cars1 = pd.read_csv("https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv")

cars2 = pd.read_csv("https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv")

cars1.head()
# cars2.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,NaN,NaN,NaN,NaN,NaN
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,NaN,NaN,NaN,NaN,NaN
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,NaN,NaN,NaN,NaN,NaN
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,NaN,NaN,NaN,NaN,NaN
4,17.0,8,302,140,3449,10.5,70,1,ford torino,NaN,NaN,NaN,NaN,NaN

### Step 4. Oops, it seems our first dataset has some unnamed blank columns, fix cars1

In [5]:
# cars1 = cars1.dropna(axis=1, how='all')

print(cars1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 198 entries, 0 to 197
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           198 non-null    float64
 1   cylinders     198 non-null    int64
 2   displacement  198 non-null    int64
 3   horsepower    198 non-null    object
 4   weight        198 non-null    int64
 5   acceleration  198 non-null    float64
 6   model         198 non-null    int64
 7   origin        198 non-null    int64
 8   car           198 non-null    object
 9   Unnamed: 9    0 non-null      float64
 10  Unnamed: 10   0 non-null      float64
 11  Unnamed: 11   0 non-null      float64
 12  Unnamed: 12   0 non-null      float64
 13  Unnamed: 13   0 non-null      float64
dtypes: float64(7), int64(5), object(2)
memory usage: 21.8+ KB
None

### Step 5. What is the number of observations in each dataset?

In [6]:
cars1 = cars1.dropna(axis=1, how='all')

### Step 6. Join cars1 and cars2 into a single DataFrame called cars

In [8]:
print(cars1.columns)
print(cars2.columns)

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model', 'origin', 'car'],
      dtype='object')
Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model', 'origin', 'car'],
      dtype='object')

In [9]:
cars = pd.concat([cars1, cars2], ignore_index=True)

print(cars.head())
print(cars.info())

    mpg  cylinders  displacement horsepower  weight  acceleration  model  \
0  18.0          8           307        130    3504          12.0     70
1  15.0          8           350        165    3693          11.5     70
2  18.0          8           318        150    3436          11.0     70
3  16.0          8           304        150    3433          12.0     70
4  17.0          8           302        140    3449          10.5     70

   origin                        car
0       1  chevrolet chevelle malibu
1       1          buick skylark 320
2       1         plymouth satellite
3       1              amc rebel sst
4       1                ford torino
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    int64
 3   horsepower    398 non-null    object
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model         398 non-null    int64
 7   origin        398 non-null    int64
 8   car           398 non-null    object
dtypes: float64(2), int64(5), object(2)
memory usage: 28.1+ KB
None

### Step 7. Oops, there is a column missing, called owners. Create a random number Series from 15,000 to 73,000.

In [14]:
import numpy as np

owners = np.random.randint(15000, 73001, size=len(cars))

### Step 8. Add the column owners to cars

In [15]:
cars['owners'] = owners

cars.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,owners
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,62253
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,66949
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,32149
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,22282
4,17.0,8,302,140,3449,10.5,70,1,ford torino,35116